logo: "/assets/logo.png"
description: Manual do usuário

# Use the Just the Docs theme
remote_theme: just-the-docs/just-the-docs

# Required for remote themes
plugins:
  - jekyll-remote-theme

# Optional configs
markdown: kramdown
highlighter: rouge

# Ativar navegação na barra lateral
just_the_docs:
  aux_nav: {}   # mantém limpo
  navigation_depth: 4
  show_toc: true
